EXEC USP_GET_KEY_ACCESS
SELECT
  INSECUREDESCRIPTION
 ,SENSITIVEINFO
 ,ISNULL(CONVERT(NVARCHAR(100),DECRYPTBYKEY(SENSITIVEINFO)),'') AS DECRYPTED_SENSITIVEINFO
FROM
  USR_SENSITIVEINFO
EXEC USP_GET_KEY_ACCESS
CLOSE SYMMETRIC KEY SYM_BBINFINITY