Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.2103.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Add form with move up down buttons on a collection' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "98d94e1a-8a05-41a9-8caf-bcd4ad5514d3", "3f94c107-99a8-4574-9b0d-3d95e75f8f21", "Collection Demo")>
Partial Public Class [AddFormWithMoveUpDownButtonsOnACollectionUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _locations As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of AddFormWithMoveUpDownButtonsOnACollectionLOCATIONSUIModel)
    Private WithEvents _moveup As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
    Private WithEvents _movdown As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public Sub New()
        MyBase.New()

        _locations = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of AddFormWithMoveUpDownButtonsOnACollectionLOCATIONSUIModel)
        _moveup = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        _movdown = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New System.Guid("98d94e1a-8a05-41a9-8caf-bcd4ad5514d3")
        MyBase.DataFormInstanceId = New System.Guid("3f94c107-99a8-4574-9b0d-3d95e75f8f21")
        MyBase.RecordType = "Collection Demo"
        MyBase.FORMHEADER.Value = "Collection with move up down buttons"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/AddFormWithMoveUpDownButtonsOnACollection.html"

        '
        '_locations
        '
        _locations.Name = "LOCATIONS"
        _locations.Caption = "Locations"
        Me.Fields.Add(_locations)
        '
        '_moveup
        '
        _moveup.Name = "MOVEUP"
        _moveup.Caption = "Move up"
        Me.Actions.Add(_moveup)
        '
        '_movdown
        '
        _movdown.Name = "MOVDOWN"
        _movdown.Caption = "Move down"
        Me.Actions.Add(_movdown)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Locations
    ''' </summary>
    <System.ComponentModel.Description("Locations")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public ReadOnly Property [LOCATIONS]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of AddFormWithMoveUpDownButtonsOnACollectionLOCATIONSUIModel)
        Get
            Return _locations
        End Get
    End Property
    
    ''' <summary>
    ''' Move up
    ''' </summary>
    <System.ComponentModel.Description("Move up")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public ReadOnly Property [MOVEUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _moveup
        End Get
    End Property
    
    ''' <summary>
    ''' Move down
    ''' </summary>
    <System.ComponentModel.Description("Move down")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public ReadOnly Property [MOVDOWN]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _movdown
        End Get
    End Property
    
End Class
