Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.2103.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'All Addresses Data List' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModelMetadata("80758453-2497-4ae0-8bcc-f7f70064ef4b")>
Partial Public Class [AllAddressesDataListUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _countryid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of System.Guid)
    Private WithEvents _stateid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of System.Guid)

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public Sub New()
        MyBase.New()

        _countryid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of System.Guid)
        _stateid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of System.Guid)

        MyBase.DataListId = New System.Guid("80758453-2497-4ae0-8bcc-f7f70064ef4b")
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/AllAddressesDataList.html"

        '
        '_countryid
        '
        _countryid.Name = "COUNTRYID"
        _countryid.Caption = "Country"
        _countryid.SimpleDataListId = New System.Guid("c9649672-353d-42e8-8c25-4d34bbabfbba")
        Me.Fields.Add(_countryid)
        '
        '_stateid
        '
        _stateid.Name = "STATEID"
        _stateid.Caption = "State"
        _stateid.SimpleDataListId = New System.Guid("b46d36d1-d3ed-4f6e-91da-89b6c88ca0c6")
        _stateid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("COUNTRYID", "Fields!COUNTRYID"))
        Me.Fields.Add(_stateid)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Country
    ''' </summary>
    <System.ComponentModel.Description("Country")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public ReadOnly Property [COUNTRYID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of System.Guid)
        Get
            Return _countryid
        End Get
    End Property
    
    ''' <summary>
    ''' State
    ''' </summary>
    <System.ComponentModel.Description("State")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public ReadOnly Property [STATEID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of System.Guid)
        Get
            Return _stateid
        End Get
    End Property
    
End Class
