Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.3405.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Calendar View Form Extension' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "2e1b2a10-dfae-4d62-a8b8-ce69d407109d", "5f5f5638-29e0-498c-bdb1-daf1019835f2", "Calendar Catalog ID + Context ID")>
Partial Public Class [CalendarViewFormExtensionUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _placeholder As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public Sub New()
        MyBase.New()

        _placeholder = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New System.Guid("2e1b2a10-dfae-4d62-a8b8-ce69d407109d")
        MyBase.DataFormInstanceId = New System.Guid("5f5f5638-29e0-498c-bdb1-daf1019835f2")
        MyBase.RecordType = "Calendar Catalog ID + Context ID"
        MyBase.ExtensionTabCaption = "Extended fields"

        '
        '_placeholder
        '
        _placeholder.Name = "PLACEHOLDER"
        _placeholder.Caption = "PLACEHOLDER"
        _placeholder.Visible = False
        _placeholder.DBReadOnly = True
        Me.Fields.Add(_placeholder)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [PLACEHOLDER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _placeholder
        End Get
    End Property
    
End Class
