Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.4000.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'CheckboxListFilterDataListADDRESSTYPECODES' data form
''' </summary>
Partial Public Class [CheckboxListFilterDataListADDRESSTYPECODESUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _addresstypecodedescription As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _addresstypecodeinclude As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _addresstypecodeid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.4000.0")> _
    Public Sub New()
        MyBase.New()

        _addresstypecodedescription = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _addresstypecodeinclude = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _addresstypecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField

        '
        '_addresstypecodedescription
        '
        _addresstypecodedescription.Name = "ADDRESSTYPECODEDESCRIPTION"
        _addresstypecodedescription.Caption = "ADDRESSTYPECODEDESCRIPTION"
        Me.Fields.Add(_addresstypecodedescription)
        '
        '_addresstypecodeinclude
        '
        _addresstypecodeinclude.Name = "ADDRESSTYPECODEINCLUDE"
        _addresstypecodeinclude.Caption = "ADDRESSTYPECODEINCLUDE"
        Me.Fields.Add(_addresstypecodeinclude)
        '
        '_addresstypecodeid
        '
        _addresstypecodeid.Name = "ADDRESSTYPECODEID"
        _addresstypecodeid.Caption = "ADDRESSTYPECODEID"
        _addresstypecodeid.Visible = False
        Me.Fields.Add(_addresstypecodeid)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.4000.0")> _
    Public ReadOnly Property [ADDRESSTYPECODEDESCRIPTION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _addresstypecodedescription
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.4000.0")> _
    Public ReadOnly Property [ADDRESSTYPECODEINCLUDE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _addresstypecodeinclude
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.4000.0")> _
    Public ReadOnly Property [ADDRESSTYPECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _addresstypecodeid
        End Get
    End Property
    
End Class
