Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.4000.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Checkbox List Filter Data List' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModelMetadata("7b190f5c-773f-4dd4-b97a-35aee8dc165a")>
Partial Public Class [CheckboxListFilterDataListUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the ADDRESSINCLUDECODE property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.4000.0")> _
    Public Enum ADDRESSINCLUDECODES As Integer
        [AllAddressTypes] = 0
        [SelectedAddressTypes] = 1
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _addressincludecode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ADDRESSINCLUDECODES))
    Private WithEvents _addresstypecodes As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of CheckboxListFilterDataListADDRESSTYPECODESUIModel)

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.4000.0")> _
    Public Sub New()
        MyBase.New()

        _addressincludecode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ADDRESSINCLUDECODES))
        _addresstypecodes = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of CheckboxListFilterDataListADDRESSTYPECODESUIModel)

        MyBase.DataListId = New System.Guid("7b190f5c-773f-4dd4-b97a-35aee8dc165a")
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/CheckboxListFilterDataList.html"

        '
        '_addressincludecode
        '
        _addressincludecode.Name = "ADDRESSINCLUDECODE"
        _addressincludecode.Caption = "Address types to include"
        _addressincludecode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ADDRESSINCLUDECODES)) With {.Value = ADDRESSINCLUDECODES.[AllAddressTypes], .Translation = "All address types"})
        _addressincludecode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of ADDRESSINCLUDECODES)) With {.Value = ADDRESSINCLUDECODES.[SelectedAddressTypes], .Translation = "Selected address types"})
        Me.Fields.Add(_addressincludecode)
        '
        '_addresstypecodes
        '
        _addresstypecodes.Name = "ADDRESSTYPECODES"
        _addresstypecodes.Caption = "Address types"
        Me.Fields.Add(_addresstypecodes)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Address types to include
    ''' </summary>
    <System.ComponentModel.Description("Address types to include")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.4000.0")> _
    Public ReadOnly Property [ADDRESSINCLUDECODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of ADDRESSINCLUDECODES))
        Get
            Return _addressincludecode
        End Get
    End Property
    
    ''' <summary>
    ''' Address types
    ''' </summary>
    <System.ComponentModel.Description("Address types")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.4000.0")> _
    Public ReadOnly Property [ADDRESSTYPECODES]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of CheckboxListFilterDataListADDRESSTYPECODESUIModel)
        Get
            Return _addresstypecodes
        End Get
    End Property
    
End Class
