Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.2103.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Collection Driven SDL Add Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "4c259b92-0f57-40f3-bf9a-6d0e853c2932", "3f94c107-99a8-4574-9b0d-3d95e75f8f21", "Collection Driven SDL")>
Partial Public Class [CollectionDrivenSDLAddDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _locations As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of CollectionDrivenSDLAddDataFormLOCATIONSUIModel)

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public Sub New()
        MyBase.New()

        _locations = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of CollectionDrivenSDLAddDataFormLOCATIONSUIModel)

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New System.Guid("4c259b92-0f57-40f3-bf9a-6d0e853c2932")
        MyBase.DataFormInstanceId = New System.Guid("3f94c107-99a8-4574-9b0d-3d95e75f8f21")
        MyBase.RecordType = "Collection Driven SDL"
        MyBase.FORMHEADER.Value = "Driven SDL within a collection"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/CollectionDrivenSDLAddDataForm.html"

        '
        '_locations
        '
        _locations.Name = "LOCATIONS"
        _locations.Caption = "Locations"
        Me.Fields.Add(_locations)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Locations
    ''' </summary>
    <System.ComponentModel.Description("Locations")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public ReadOnly Property [LOCATIONS]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of CollectionDrivenSDLAddDataFormLOCATIONSUIModel)
        Get
            Return _locations
        End Get
    End Property
    
End Class
