Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.3405.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Constituent Interaction View Form Extension' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "759e6600-5cef-436c-af5e-87eea6fdc2f6", "5ee1541a-fbc1-42ea-b76d-897d8d7a2de0", "Constituent Interaction")>
Partial Public Class [ConstituentInteractionViewFormExtensionUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _firstname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _keyname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _age As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _relativeinfo As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ConstituentInteractionViewFormExtensionRELATIVEINFOUIModel)
    Private WithEvents _recordcount As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _currentindex As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _nextrecord As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
    Private WithEvents _priorrecord As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public Sub New()
        MyBase.New()

        _firstname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _keyname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _age = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _relativeinfo = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ConstituentInteractionViewFormExtensionRELATIVEINFOUIModel)
        _recordcount = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _currentindex = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _nextrecord = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        _priorrecord = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New System.Guid("759e6600-5cef-436c-af5e-87eea6fdc2f6")
        MyBase.DataFormInstanceId = New System.Guid("5ee1541a-fbc1-42ea-b76d-897d8d7a2de0")
        MyBase.RecordType = "Constituent Interaction"
        MyBase.ExtensionTabCaption = "Extended fields"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/ConstituentInteractionViewFormExtension.html"

        '
        '_firstname
        '
        _firstname.Name = "FIRSTNAME"
        _firstname.Caption = "First name"
        _firstname.DBReadOnly = True
        _firstname.MaxLength = 200
        Me.Fields.Add(_firstname)
        '
        '_keyname
        '
        _keyname.Name = "KEYNAME"
        _keyname.Caption = "Last name"
        _keyname.DBReadOnly = True
        _keyname.MaxLength = 200
        Me.Fields.Add(_keyname)
        '
        '_age
        '
        _age.Name = "AGE"
        _age.Caption = "Age"
        _age.DBReadOnly = True
        Me.Fields.Add(_age)
        '
        '_relativeinfo
        '
        _relativeinfo.Name = "RELATIVEINFO"
        _relativeinfo.Caption = "Relatives"
        _relativeinfo.DBReadOnly = True
        Me.Fields.Add(_relativeinfo)
        '
        '_recordcount
        '
        _recordcount.Name = "RECORDCOUNT"
        _recordcount.Caption = "Total"
        _recordcount.DBReadOnly = True
        Me.Fields.Add(_recordcount)
        '
        '_currentindex
        '
        _currentindex.Name = "CURRENTINDEX"
        _currentindex.Caption = "Current"
        _currentindex.DBReadOnly = True
        Me.Fields.Add(_currentindex)
        '
        '_nextrecord
        '
        _nextrecord.Name = "NEXTRECORD"
        _nextrecord.Caption = "Next"
        Me.Actions.Add(_nextrecord)
        '
        '_priorrecord
        '
        _priorrecord.Name = "PRIORRECORD"
        _priorrecord.Caption = "Back"
        Me.Actions.Add(_priorrecord)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' First name
    ''' </summary>
    <System.ComponentModel.Description("First name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [FIRSTNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _firstname
        End Get
    End Property
    
    ''' <summary>
    ''' Last name
    ''' </summary>
    <System.ComponentModel.Description("Last name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [KEYNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _keyname
        End Get
    End Property
    
    ''' <summary>
    ''' Age
    ''' </summary>
    <System.ComponentModel.Description("Age")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [AGE]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _age
        End Get
    End Property
    
    ''' <summary>
    ''' Relatives
    ''' </summary>
    <System.ComponentModel.Description("Relatives")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [RELATIVEINFO]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ConstituentInteractionViewFormExtensionRELATIVEINFOUIModel)
        Get
            Return _relativeinfo
        End Get
    End Property
    
    ''' <summary>
    ''' Total
    ''' </summary>
    <System.ComponentModel.Description("Total")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [RECORDCOUNT]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _recordcount
        End Get
    End Property
    
    ''' <summary>
    ''' Current
    ''' </summary>
    <System.ComponentModel.Description("Current")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [CURRENTINDEX]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _currentindex
        End Get
    End Property
    
    ''' <summary>
    ''' Next
    ''' </summary>
    <System.ComponentModel.Description("Next")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [NEXTRECORD]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _nextrecord
        End Get
    End Property
    
    ''' <summary>
    ''' Back
    ''' </summary>
    <System.ComponentModel.Description("Back")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [PRIORRECORD]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _priorrecord
        End Get
    End Property
    
End Class
