Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.2103.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Constituent HTML Add Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "3afd01ca-f043-4638-bbf5-13accc5357ed", "a6b96780-0731-4ad6-9937-a33cb992e608", "Constituent HTML", "Constituent")>
Partial Public Class [ConstituentHTMLAddFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _htmlvalue As Global.Blackbaud.AppFx.UIModeling.Core.HtmlField
    Private WithEvents _plaintextvalue As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public Sub New()
        MyBase.New()

        _htmlvalue = New Global.Blackbaud.AppFx.UIModeling.Core.HtmlField
        _plaintextvalue = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New System.Guid("3afd01ca-f043-4638-bbf5-13accc5357ed")
        MyBase.DataFormInstanceId = New System.Guid("a6b96780-0731-4ad6-9937-a33cb992e608")
        MyBase.RecordType = "Constituent HTML"
        MyBase.ContextRecordType = "Constituent"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/html/ConstituentHTMLAddForm.html"

        '
        '_htmlvalue
        '
        _htmlvalue.Name = "HTMLVALUE"
        _htmlvalue.Caption = "Html"
        Me.Fields.Add(_htmlvalue)
        '
        '_plaintextvalue
        '
        _plaintextvalue.Name = "PLAINTEXTVALUE"
        _plaintextvalue.Caption = "Plain text"
        _plaintextvalue.Visible = False
        Me.Fields.Add(_plaintextvalue)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Html
    ''' </summary>
    <System.ComponentModel.Description("Html")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public ReadOnly Property [HTMLVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.HtmlField
        Get
            Return _htmlvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Plain text
    ''' </summary>
    <System.ComponentModel.Description("Plain text")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public ReadOnly Property [PLAINTEXTVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _plaintextvalue
        End Get
    End Property
    
End Class
