Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.2902.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Constituent Address Picklist' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "6ce646c5-50d1-475a-bdf1-0c17e3c6f43c", "0aeced44-c0c4-430a-9d4f-b876cf6b4d7b", "Address", "Constituent")>
Partial Public Class [ConstituentAddressPicklistUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _availableaddresses As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ConstituentAddressPicklistAVAILABLEADDRESSESUIModel)
    Private WithEvents _selectedaddresses As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ConstituentAddressPicklistSELECTEDADDRESSESUIModel)
    Private WithEvents _select As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
    Private WithEvents _deselect As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2902.0")> _
    Public Sub New()
        MyBase.New()

        _availableaddresses = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ConstituentAddressPicklistAVAILABLEADDRESSESUIModel)
        _selectedaddresses = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ConstituentAddressPicklistSELECTEDADDRESSESUIModel)
        _select = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        _deselect = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New System.Guid("6ce646c5-50d1-475a-bdf1-0c17e3c6f43c")
        MyBase.DataFormInstanceId = New System.Guid("0aeced44-c0c4-430a-9d4f-b876cf6b4d7b")
        MyBase.RecordType = "Address"
        MyBase.ContextRecordType = "Constituent"
        MyBase.FORMHEADER.Value = "Select addresses"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/ConstituentAddressPicklist.html"

        '
        '_availableaddresses
        '
        _availableaddresses.Name = "AVAILABLEADDRESSES"
        _availableaddresses.Caption = "Available addresses"
        Me.Fields.Add(_availableaddresses)
        '
        '_selectedaddresses
        '
        _selectedaddresses.Name = "SELECTEDADDRESSES"
        _selectedaddresses.Caption = "Selected addresses"
        Me.Fields.Add(_selectedaddresses)
        '
        '_select
        '
        _select.Name = "SELECT"
        _select.Caption = ""
        _select.ImageKey = "CATALOG:Training.Catalog,Training.Catalog.right-arrow_16.png"
        Me.Actions.Add(_select)
        '
        '_deselect
        '
        _deselect.Name = "DESELECT"
        _deselect.Caption = ""
        _deselect.ImageKey = "CATALOG:Training.Catalog,Training.Catalog.left-arrow_16.png"
        Me.Actions.Add(_deselect)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Available addresses
    ''' </summary>
    <System.ComponentModel.Description("Available addresses")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2902.0")> _
    Public ReadOnly Property [AVAILABLEADDRESSES]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ConstituentAddressPicklistAVAILABLEADDRESSESUIModel)
        Get
            Return _availableaddresses
        End Get
    End Property
    
    ''' <summary>
    ''' Selected addresses
    ''' </summary>
    <System.ComponentModel.Description("Selected addresses")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2902.0")> _
    Public ReadOnly Property [SELECTEDADDRESSES]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ConstituentAddressPicklistSELECTEDADDRESSESUIModel)
        Get
            Return _selectedaddresses
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2902.0")> _
    Public ReadOnly Property [SELECT]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _select
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2902.0")> _
    Public ReadOnly Property [DESELECT]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _deselect
        End Get
    End Property
    
End Class
