Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.3501.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Constituent Pet Add Data Form (Stored Procedure)' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "71638530-465f-4a01-ad1e-ffdc5e6c1041", "fc0bf5fd-8763-4bff-b65d-06053344eaf9", "Constituent Pet", "Constituent")>
Partial Public Class [ConstituentPetAddDataFormStoredProcedureUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _petname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _petimage As Global.Blackbaud.AppFx.UIModeling.Core.FileField(Of Byte())
    Private WithEvents _petimagefilename As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public Sub New()
        MyBase.New()

        _petname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _petimage = New Global.Blackbaud.AppFx.UIModeling.Core.FileField(Of Byte())
        _petimagefilename = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New System.Guid("71638530-465f-4a01-ad1e-ffdc5e6c1041")
        MyBase.DataFormInstanceId = New System.Guid("fc0bf5fd-8763-4bff-b65d-06053344eaf9")
        MyBase.RecordType = "Constituent Pet"
        MyBase.ContextRecordType = "Constituent"
        MyBase.FORMHEADER.Value = "Add a constituent pet"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/ConstituentPetAddDataFormStoredProcedure.html"

        '
        '_petname
        '
        _petname.Name = "PETNAME"
        _petname.Caption = "Pet name"
        _petname.MaxLength = 1000
        Me.Fields.Add(_petname)
        '
        '_petimage
        '
        _petimage.Name = "PETIMAGE"
        _petimage.Caption = "Pet image"
        _petimage.FileNameFieldId = "PETIMAGEFILENAME"
        _petimage.ShowProgressUI = True
        _petimage.UploadType = Global.Blackbaud.AppFx.UIModeling.Core.FileFieldUploadType.OnSave
        Me.Fields.Add(_petimage)
        '
        '_petimagefilename
        '
        _petimagefilename.Name = "PETIMAGEFILENAME"
        _petimagefilename.Caption = "Pet image file"
        _petimagefilename.Required = True
        _petimagefilename.MaxLength = 500
        Me.Fields.Add(_petimagefilename)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Pet name
    ''' </summary>
    <System.ComponentModel.Description("Pet name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public ReadOnly Property [PETNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _petname
        End Get
    End Property
    
    ''' <summary>
    ''' Pet image
    ''' </summary>
    <System.ComponentModel.Description("Pet image")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public ReadOnly Property [PETIMAGE]() As Global.Blackbaud.AppFx.UIModeling.Core.FileField(Of Byte())
        Get
            Return _petimage
        End Get
    End Property
    
    ''' <summary>
    ''' Pet image file
    ''' </summary>
    <System.ComponentModel.Description("Pet image file")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public ReadOnly Property [PETIMAGEFILENAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _petimagefilename
        End Get
    End Property
    
End Class
