Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.3405.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'ConstituentInteractionViewFormExtensionRELATIVEINFO' data form
''' </summary>
Partial Public Class [ConstituentInteractionViewFormExtensionRELATIVEINFOUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _firstname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _keyname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _age As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public Sub New()
        MyBase.New()

        _firstname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _keyname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _age = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        '
        '_firstname
        '
        _firstname.Name = "FIRSTNAME"
        _firstname.Caption = "First name"
        _firstname.DBReadOnly = True
        Me.Fields.Add(_firstname)
        '
        '_keyname
        '
        _keyname.Name = "KEYNAME"
        _keyname.Caption = "Last name"
        _keyname.DBReadOnly = True
        Me.Fields.Add(_keyname)
        '
        '_age
        '
        _age.Name = "AGE"
        _age.Caption = "Age"
        _age.DBReadOnly = True
        Me.Fields.Add(_age)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' First name
    ''' </summary>
    <System.ComponentModel.Description("First name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [FIRSTNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _firstname
        End Get
    End Property
    
    ''' <summary>
    ''' Last name
    ''' </summary>
    <System.ComponentModel.Description("Last name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [KEYNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _keyname
        End Get
    End Property
    
    ''' <summary>
    ''' Age
    ''' </summary>
    <System.ComponentModel.Description("Age")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [AGE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _age
        End Get
    End Property
    
End Class
