Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.3501.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Copy Event Stub Edit Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "3d8dc684-4338-4144-9274-f4cbe757d2b9", "0d681f4b-217e-425f-b851-8eac5116a9d0", "Event")>
Partial Public Class [CopyEventStubEditDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _neweventid As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _neweventurl As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public Sub New()
        MyBase.New()

        _neweventid = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _neweventurl = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New System.Guid("3d8dc684-4338-4144-9274-f4cbe757d2b9")
        MyBase.DataFormInstanceId = New System.Guid("0d681f4b-217e-425f-b851-8eac5116a9d0")
        MyBase.RecordType = "Event"
        MyBase.FORMHEADER.Value = "Copy this event"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/CopyEventStubEditDataForm.html"

        '
        '_neweventid
        '
        _neweventid.Name = "NEWEVENTID"
        _neweventid.Caption = "NEWEVENTID"
        _neweventid.MaxLength = 36
        Me.Fields.Add(_neweventid)
        '
        '_neweventurl
        '
        _neweventurl.Name = "NEWEVENTURL"
        _neweventurl.Caption = "NEWEVENTURL"
        _neweventurl.MaxLength = 2000
        Me.Fields.Add(_neweventurl)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public ReadOnly Property [NEWEVENTID]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _neweventid
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public ReadOnly Property [NEWEVENTURL]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _neweventurl
        End Get
    End Property
    
End Class
