Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.3000.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Dynamic Behavior Demo Add Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "c34b926b-4432-4e8f-bbf2-6cd8d11cc79c", "8d72abb4-11da-4533-bdc6-89bec13bf291", "Constituent")>
Partial Public Class [DynamicBehaviorDemoAddDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _makenotebigger As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _note As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3000.0")> _
    Public Sub New()
        MyBase.New()

        _makenotebigger = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _note = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New System.Guid("c34b926b-4432-4e8f-bbf2-6cd8d11cc79c")
        MyBase.DataFormInstanceId = New System.Guid("8d72abb4-11da-4533-bdc6-89bec13bf291")
        MyBase.RecordType = "Constituent"
        MyBase.FORMHEADER.Value = "Dynamic behavior through JavaScript"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/DynamicBehaviorDemoAddDataForm.html"

        '
        '_makenotebigger
        '
        _makenotebigger.Name = "MAKENOTEBIGGER"
        _makenotebigger.Caption = "I need more room for my note"
        Me.Fields.Add(_makenotebigger)
        '
        '_note
        '
        _note.Name = "NOTE"
        _note.Caption = "Note"
        _note.Multiline = True
        Me.Fields.Add(_note)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' I need more room for my note
    ''' </summary>
    <System.ComponentModel.Description("I need more room for my note")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3000.0")> _
    Public ReadOnly Property [MAKENOTEBIGGER]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _makenotebigger
        End Get
    End Property
    
    ''' <summary>
    ''' Note
    ''' </summary>
    <System.ComponentModel.Description("Note")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3000.0")> _
    Public ReadOnly Property [NOTE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _note
        End Get
    End Property
    
End Class
