Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.3501.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Edit Data Form Template Spec Edit Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "bb08bdb7-1f7a-4a44-9730-c14b28deaf80", "e6f97eb6-d46f-465d-8f75-3ee310edf54f", "Edit Data Form Template Spec")>
Partial Public Class [EditDataFormTemplateSpecEditDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _field1 As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _dummyid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public Sub New()
        MyBase.New()

        _field1 = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _dummyid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New System.Guid("bb08bdb7-1f7a-4a44-9730-c14b28deaf80")
        MyBase.DataFormInstanceId = New System.Guid("e6f97eb6-d46f-465d-8f75-3ee310edf54f")
        MyBase.RecordType = "Edit Data Form Template Spec"
        MyBase.FORMHEADER.Value = "Edit an edit data form template spec"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/EditDataFormTemplateSpecEditDataForm.html"

        '
        '_field1
        '
        _field1.Name = "FIELD1"
        _field1.Caption = "Field 1"
        _field1.MaxLength = 10
        Me.Fields.Add(_field1)
        '
        '_dummyid
        '
        _dummyid.Name = "DUMMYID"
        _dummyid.Caption = "Dummy ID"
        _dummyid.Visible = False
        Me.Fields.Add(_dummyid)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Field 1
    ''' </summary>
    <System.ComponentModel.Description("Field 1")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public ReadOnly Property [FIELD1]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _field1
        End Get
    End Property
    
    ''' <summary>
    ''' Dummy ID
    ''' </summary>
    <System.ComponentModel.Description("Dummy ID")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public ReadOnly Property [DUMMYID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _dummyid
        End Get
    End Property
    
End Class
