Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.3501.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Global Change Search' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.SearchListUIModelMetadata("947fb797-d6fd-4e0e-8bfe-84a0bbf64eca", "Global Change")>
Partial Public Class [GlobalChangeSearchUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.SearchListUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _globalchangename As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public Sub New()
        MyBase.New()

        _globalchangename = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.SearchListId = New System.Guid("947fb797-d6fd-4e0e-8bfe-84a0bbf64eca")
        MyBase.SearchRecordType = "Global Change"
        MyBase.FORMHEADER.Value = "Global Change Search"
        MyBase.TranslationFunctionId = New System.Guid("fb7f7cb2-7047-4473-8570-3fba43da3841")
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/GlobalChangeSearch.html"

        '
        '_globalchangename
        '
        _globalchangename.Name = "GLOBALCHANGENAME"
        _globalchangename.Caption = "Name"
        _globalchangename.MaxLength = 100
        Me.Fields.Add(_globalchangename)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Name
    ''' </summary>
    <System.ComponentModel.Description("Name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public ReadOnly Property [GLOBALCHANGENAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _globalchangename
        End Get
    End Property
    
End Class
