Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.2103.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'HTML View Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "63344316-05d4-4009-ab61-7107369c6f12", "f22dd105-3dac-4045-8320-e9f77069528a", "HTML")>
Partial Public Class [HTMLViewDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _htmlfield As Global.Blackbaud.AppFx.UIModeling.Core.HtmlField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public Sub New()
        MyBase.New()

        _htmlfield = New Global.Blackbaud.AppFx.UIModeling.Core.HtmlField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New System.Guid("63344316-05d4-4009-ab61-7107369c6f12")
        MyBase.DataFormInstanceId = New System.Guid("f22dd105-3dac-4045-8320-e9f77069528a")
        MyBase.RecordType = "HTML"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/HTMLViewDataForm.html"

        '
        '_htmlfield
        '
        _htmlfield.Name = "HTMLFIELD"
        _htmlfield.Caption = "Note"
        _htmlfield.DBReadOnly = True
        Me.Fields.Add(_htmlfield)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Note
    ''' </summary>
    <System.ComponentModel.Description("Note")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2103.0")> _
    Public ReadOnly Property [HTMLFIELD]() As Global.Blackbaud.AppFx.UIModeling.Core.HtmlField
        Get
            Return _htmlfield
        End Get
    End Property
    
End Class
