Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.2902.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Image Demo View Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "ec1f24a9-3e1a-49b9-adec-de173549a7c5", "a29ee034-5c8b-4762-8745-0af7a617bf28", "Image Demo")>
Partial Public Class [ImageDemoViewDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _decisionfield As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _testimage As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2902.0")> _
    Public Sub New()
        MyBase.New()

        _decisionfield = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _testimage = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New System.Guid("ec1f24a9-3e1a-49b9-adec-de173549a7c5")
        MyBase.DataFormInstanceId = New System.Guid("a29ee034-5c8b-4762-8745-0af7a617bf28")
        MyBase.RecordType = "Image Demo"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/ImageDemoViewDataForm.html"

        '
        '_decisionfield
        '
        _decisionfield.Name = "DECISIONFIELD"
        _decisionfield.Caption = "Decision field"
        _decisionfield.DBReadOnly = True
        Me.Fields.Add(_decisionfield)
        '
        '_testimage
        '
        _testimage.Name = "TESTIMAGE"
        _testimage.Caption = "TESTIMAGE"
        _testimage.DBReadOnly = True
        Me.Fields.Add(_testimage)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Decision field
    ''' </summary>
    <System.ComponentModel.Description("Decision field")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2902.0")> _
    Public ReadOnly Property [DECISIONFIELD]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        Get
            Return _decisionfield
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2902.0")> _
    Public ReadOnly Property [TESTIMAGE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _testimage
        End Get
    End Property
    
End Class
