Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.3501.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Naming Opportunity Add Form Add Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "89327343-4573-4803-a4ec-aa66897efc90", "9e4bfd9b-fb67-4255-81ce-b52d0a436ab7", "Naming Opportunity", "Naming Opportunity")>
Partial Public Class [NamingOpportunityAddFormAddDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _field1 As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public Sub New()
        MyBase.New()

        _field1 = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New System.Guid("89327343-4573-4803-a4ec-aa66897efc90")
        MyBase.DataFormInstanceId = New System.Guid("9e4bfd9b-fb67-4255-81ce-b52d0a436ab7")
        MyBase.RecordType = "Naming Opportunity"
        MyBase.ContextRecordType = "Naming Opportunity"
        MyBase.ExtensionTabCaption = "Extended fields"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/NamingOpportunityAddFormAddDataForm.html"

        '
        '_field1
        '
        _field1.Name = "FIELD1"
        _field1.Caption = "FIELD1"
        Me.Fields.Add(_field1)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public ReadOnly Property [FIELD1]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _field1
        End Get
    End Property
    
End Class
