Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.3501.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Order Of Operations Edit Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "02ca5448-5d45-4847-9b6b-19cb53c6e64f", "6eb2ff47-5a48-4be2-8daf-9798482c82a5", "Constituent")>
Partial Public Class [OrderOfOperationsEditDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _firstname As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public Sub New()
        MyBase.New()

        _firstname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New System.Guid("02ca5448-5d45-4847-9b6b-19cb53c6e64f")
        MyBase.DataFormInstanceId = New System.Guid("6eb2ff47-5a48-4be2-8daf-9798482c82a5")
        MyBase.RecordType = "Constituent"
        MyBase.FORMHEADER.Value = "Edit an order of operations"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/OrderOfOperationsEditDataForm.html"

        '
        '_firstname
        '
        _firstname.Name = "FIRSTNAME"
        _firstname.Caption = "1st name"
        _firstname.MaxLength = 100
        Me.Fields.Add(_firstname)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' 1st name
    ''' </summary>
    <System.ComponentModel.Description("1st name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public ReadOnly Property [FIRSTNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _firstname
        End Get
    End Property
    
End Class
