Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.3405.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Params From URL Data List' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModelMetadata("ab5d089f-eaf5-4ce7-bc0c-64c8144c271d")>
Partial Public Class [ParamsFromURLDataListUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _firstname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _keyname As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public Sub New()
        MyBase.New()

        _firstname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _keyname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.DataListId = New System.Guid("ab5d089f-eaf5-4ce7-bc0c-64c8144c271d")
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/ParamsFromURLDataList.html"

        '
        '_firstname
        '
        _firstname.Name = "FIRSTNAME"
        _firstname.Caption = "First name contains"
        _firstname.MaxLength = 100
        Me.Fields.Add(_firstname)
        '
        '_keyname
        '
        _keyname.Name = "KEYNAME"
        _keyname.Caption = "Last name contains"
        _keyname.MaxLength = 200
        Me.Fields.Add(_keyname)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' First name contains
    ''' </summary>
    <System.ComponentModel.Description("First name contains")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [FIRSTNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _firstname
        End Get
    End Property
    
    ''' <summary>
    ''' Last name contains
    ''' </summary>
    <System.ComponentModel.Description("Last name contains")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [KEYNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _keyname
        End Get
    End Property
    
End Class
