Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.3405.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Prospect Research Request Add Form Add Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "5dd9eed7-4e69-4ffb-a61b-9021e4c26ff9", "baddc141-d435-40f5-9348-f58fca05eb3f", "Prospect Research Request Add Form", "Prospect Research Request")>
Partial Public Class [ProspectResearchRequestAddFormAddDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _defaultprospectid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public Sub New()
        MyBase.New()

        _defaultprospectid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New System.Guid("5dd9eed7-4e69-4ffb-a61b-9021e4c26ff9")
        MyBase.DataFormInstanceId = New System.Guid("baddc141-d435-40f5-9348-f58fca05eb3f")
        MyBase.RecordType = "Prospect Research Request Add Form"
        MyBase.ContextRecordType = "Prospect Research Request"
        MyBase.FORMHEADER.Value = "Add a prospect research request add form"
        MyBase.ExtensionTabCaption = "Extended fields"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/ProspectResearchRequestAddFormAddDataForm.html"

        '
        '_defaultprospectid
        '
        _defaultprospectid.Name = "DEFAULTPROSPECTID"
        _defaultprospectid.Caption = "Default prospect"
        Me.Fields.Add(_defaultprospectid)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Default prospect
    ''' </summary>
    <System.ComponentModel.Description("Default prospect")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3405.0")> _
    Public ReadOnly Property [DEFAULTPROSPECTID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _defaultprospectid
        End Get
    End Property
    
End Class
