Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.3501.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Redirect Message Add Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "b47fe400-d0b9-43e1-b39f-49234ac908d0", "c23592d5-5cdb-47a5-948c-56d4c4774c64", "Redirect Message", "Constituent")>
Partial Public Class [RedirectMessageAddDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _isprospect As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _firstname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _gotowealthandratingspage As Global.Blackbaud.AppFx.UIModeling.Core.ShowPageUIAction

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public Sub New()
        MyBase.New()

        _isprospect = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _firstname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _gotowealthandratingspage = New Global.Blackbaud.AppFx.UIModeling.Core.ShowPageUIAction

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New System.Guid("b47fe400-d0b9-43e1-b39f-49234ac908d0")
        MyBase.DataFormInstanceId = New System.Guid("c23592d5-5cdb-47a5-948c-56d4c4774c64")
        MyBase.RecordType = "Redirect Message"
        MyBase.ContextRecordType = "Constituent"
        MyBase.FORMHEADER.Value = "Add a redirect message"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/training/RedirectMessageAddDataForm.html"

        '
        '_isprospect
        '
        _isprospect.Name = "ISPROSPECT"
        _isprospect.Caption = "ISPROSPECT"
        _isprospect.DBReadOnly = True
        Me.Fields.Add(_isprospect)
        '
        '_firstname
        '
        _firstname.Name = "FIRSTNAME"
        _firstname.Caption = "First name"
        _firstname.MaxLength = 100
        Me.Fields.Add(_firstname)
        '
        '_gotowealthandratingspage
        '
        _gotowealthandratingspage.Name = "GOTOWEALTHANDRATINGSPAGE"
        _gotowealthandratingspage.Caption = "View wealth and ratings"
        _gotowealthandratingspage.PageId = New System.Guid("a6c2fffb-2df0-44c9-8238-2ae74443f1de")
        _gotowealthandratingspage.ContextIdDefinition = "Form!CURRENTRECORDID"
        Me.Actions.Add(_gotowealthandratingspage)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public ReadOnly Property [ISPROSPECT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _isprospect
        End Get
    End Property
    
    ''' <summary>
    ''' First name
    ''' </summary>
    <System.ComponentModel.Description("First name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public ReadOnly Property [FIRSTNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _firstname
        End Get
    End Property
    
    ''' <summary>
    ''' View wealth and ratings
    ''' </summary>
    <System.ComponentModel.Description("View wealth and ratings")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3501.0")> _
    Public ReadOnly Property [GOTOWEALTHANDRATINGSPAGE]() As Global.Blackbaud.AppFx.UIModeling.Core.ShowPageUIAction
        Get
            Return _gotowealthandratingspage
        End Get
    End Property
    
End Class
